version: '3.8'

services:
  eurekabe-app:
    image: eurekabe:latest
    volumes:
      - eurekabe_storage:/var/www/html/storage
      - eurekabe_bootstrap_cache:/var/www/html/bootstrap/cache

volumes:
  eurekabe_storage:
  eurekabe_bootstrap_cache:
