version: '3.8'

services:
  app:
    image: my-laravel-app
    container_name: laravel_app
    restart: always
    volumes:
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
volumes:
  storage:
  cache:
