[variables]
COMPOSER_ALLOW_SUPERUSER="1"

[phases.build]
cmds = [
  "composer install --no-dev", 
  "npm install",
  "PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}') && echo -e 'post_max_size = 10M\nupload_max_filesize = 10M' >> $PHP_INI_PATH",
  "echo -e 'upload_max_filesize = 10M\npost_max_size = 10M' > /usr/local/etc/php/conf.d/uploads.ini"
]

[phases.setup]
cmds = ["composer install --no-dev"]

[phases.start]
cmds = [
  "php artisan storage:link",
  "chmod -R 777 storage bootstrap/cache",
  "chmod -R 777 storage public/uploads",
  "chmod -R 777 /app/public/uploads/",
  "php artisan optimize:clear"
]

[volumes]
storage = "/app/storage"