[variables]
COMPOSER_ALLOW_SUPERUSER="1"

[phases.build]
cmds = [
  "composer install --no-dev", 
  "npm install",
  "echo 'upload_max_filesize = 100M' > /app/php/conf.d/uploads.ini",
  "echo 'post_max_size = 100M' >> /app/php/conf.d/uploads.ini",
  "echo 'memory_limit = 256M' >> /app/php/conf.d/uploads.ini",
]



[phases.setup]
cmds = ["composer install --no-dev"]

[phases.start]
cmds = [
  "php artisan storage:link",
  "chmod -R 777 storage bootstrap/cache",
  "chmod -R 777 storage public/uploads",
  "chmod -R 777 /app/public/uploads/",
  "php artisan optimize:clear"
]

[volumes]
storage = "/app/storage"